// import { User } from "../type/types";

// // export const users: User[] = [
// //   {
// //     id: 1,
// //     name: "Alice",
// //     data: [
// //       {
// //         sector: "Retail",
// //         category: "Juice",
// //         spend: 200,
// //         percentChange: 5,
// //         absoluteChange: 10,
// //         date: "2023-10-01",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Snacks",
// //         spend: 150,
// //         percentChange: -2,
// //         absoluteChange: -3,
// //         date: "2023-10-05",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Software",
// //         spend: 450,
// //         percentChange: 12,
// //         absoluteChange: 54,
// //         date: "2023-10-08",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Supplements",
// //         spend: 120,
// //         percentChange: 3,
// //         absoluteChange: 3.6,
// //         date: "2023-10-12",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Accessories",
// //         spend: 280,
// //         percentChange: -5,
// //         absoluteChange: -14,
// //         date: "2023-10-15",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Clothing",
// //         spend: 320,
// //         percentChange: 8,
// //         absoluteChange: 25.6,
// //         date: "2023-10-18",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Beverages",
// //         spend: 90,
// //         percentChange: -1,
// //         absoluteChange: -0.9,
// //         date: "2023-10-22",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Materials",
// //         spend: 410,
// //         percentChange: 15,
// //         absoluteChange: 61.5,
// //         date: "2023-10-25",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Gadgets",
// //         spend: 520,
// //         percentChange: 20,
// //         absoluteChange: 104,
// //         date: "2023-10-28",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Equipment",
// //         spend: 380,
// //         percentChange: -3,
// //         absoluteChange: -11.4,
// //         date: "2023-10-31",
// //       },
// //     ],
// //   },
// //   {
// //     id: 2,
// //     name: "Bob",
// //     data: [
// //       {
// //         sector: "Industrial",
// //         category: "Tools",
// //         spend: 300,
// //         percentChange: 10,
// //         absoluteChange: 30,
// //         date: "2023-10-03",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Juice",
// //         spend: 180,
// //         percentChange: 3,
// //         absoluteChange: 5,
// //         date: "2023-10-08",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Groceries",
// //         spend: 220,
// //         percentChange: 4,
// //         absoluteChange: 8.8,
// //         date: "2023-10-11",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Hardware",
// //         spend: 510,
// //         percentChange: 18,
// //         absoluteChange: 91.8,
// //         date: "2023-10-14",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Medicines",
// //         spend: 160,
// //         percentChange: -2,
// //         absoluteChange: -3.2,
// //         date: "2023-10-17",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Parts",
// //         spend: 290,
// //         percentChange: 7,
// //         absoluteChange: 20.3,
// //         date: "2023-10-20",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Electronics",
// //         spend: 430,
// //         percentChange: 12,
// //         absoluteChange: 51.6,
// //         date: "2023-10-23",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Organic",
// //         spend: 140,
// //         percentChange: 5,
// //         absoluteChange: 7,
// //         date: "2023-10-26",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Machinery",
// //         spend: 670,
// //         percentChange: 22,
// //         absoluteChange: 147.4,
// //         date: "2023-10-29",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Services",
// //         spend: 390,
// //         percentChange: -4,
// //         absoluteChange: -15.6,
// //         date: "2023-11-01",
// //       },
// //     ],
// //   },
// //   {
// //     id: 3,
// //     name: "Charlie",
// //     data: [
// //       {
// //         sector: "Technology",
// //         category: "Software",
// //         spend: 480,
// //         percentChange: 15,
// //         absoluteChange: 72,
// //         date: "2023-10-02",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Equipment",
// //         spend: 310,
// //         percentChange: 8,
// //         absoluteChange: 24.8,
// //         date: "2023-10-06",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Furniture",
// //         spend: 420,
// //         percentChange: 10,
// //         absoluteChange: 42,
// //         date: "2023-10-09",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Bakery",
// //         spend: 110,
// //         percentChange: -3,
// //         absoluteChange: -3.3,
// //         date: "2023-10-13",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Tires",
// //         spend: 380,
// //         percentChange: 12,
// //         absoluteChange: 45.6,
// //         date: "2023-10-16",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Chemicals",
// //         spend: 540,
// //         percentChange: 18,
// //         absoluteChange: 97.2,
// //         date: "2023-10-19",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Accessories",
// //         spend: 230,
// //         percentChange: 6,
// //         absoluteChange: 13.8,
// //         date: "2023-10-22",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Diagnostics",
// //         spend: 270,
// //         percentChange: -1,
// //         absoluteChange: -2.7,
// //         date: "2023-10-25",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Appliances",
// //         spend: 590,
// //         percentChange: 20,
// //         absoluteChange: 118,
// //         date: "2023-10-28",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Dairy",
// //         spend: 130,
// //         percentChange: 2,
// //         absoluteChange: 2.6,
// //         date: "2023-10-31",
// //       },
// //     ],
// //   },
// //   {
// //     id: 4,
// //     name: "Diana",
// //     data: [
// //       {
// //         sector: "Healthcare",
// //         category: "Wellness",
// //         spend: 190,
// //         percentChange: 6,
// //         absoluteChange: 11.4,
// //         date: "2023-10-04",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Services",
// //         spend: 250,
// //         percentChange: 8,
// //         absoluteChange: 20,
// //         date: "2023-10-07",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Sports",
// //         spend: 330,
// //         percentChange: 12,
// //         absoluteChange: 39.6,
// //         date: "2023-10-10",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Meat",
// //         spend: 170,
// //         percentChange: -4,
// //         absoluteChange: -6.8,
// //         date: "2023-10-14",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Safety",
// //         spend: 410,
// //         percentChange: 14,
// //         absoluteChange: 57.4,
// //         date: "2023-10-17",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Cloud",
// //         spend: 620,
// //         percentChange: 25,
// //         absoluteChange: 155,
// //         date: "2023-10-20",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Therapy",
// //         spend: 280,
// //         percentChange: 7,
// //         absoluteChange: 19.6,
// //         date: "2023-10-23",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Batteries",
// //         spend: 350,
// //         percentChange: -2,
// //         absoluteChange: -7,
// //         date: "2023-10-26",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Books",
// //         spend: 210,
// //         percentChange: 5,
// //         absoluteChange: 10.5,
// //         date: "2023-10-29",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Produce",
// //         spend: 140,
// //         percentChange: 3,
// //         absoluteChange: 4.2,
// //         date: "2023-11-01",
// //       },
// //     ],
// //   },
// //   {
// //     id: 5,
// //     name: "Ethan",
// //     data: [
// //       {
// //         sector: "Automotive",
// //         category: "Lubricants",
// //         spend: 270,
// //         percentChange: 9,
// //         absoluteChange: 24.3,
// //         date: "2023-10-05",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Toys",
// //         spend: 180,
// //         percentChange: 4,
// //         absoluteChange: 7.2,
// //         date: "2023-10-09",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Frozen",
// //         spend: 150,
// //         percentChange: -1,
// //         absoluteChange: -1.5,
// //         date: "2023-10-12",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Packaging",
// //         spend: 390,
// //         percentChange: 13,
// //         absoluteChange: 50.7,
// //         date: "2023-10-15",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Security",
// //         spend: 480,
// //         percentChange: 17,
// //         absoluteChange: 81.6,
// //         date: "2023-10-18",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Devices",
// //         spend: 320,
// //         percentChange: 10,
// //         absoluteChange: 32,
// //         date: "2023-10-21",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Electronics",
// //         spend: 290,
// //         percentChange: -3,
// //         absoluteChange: -8.7,
// //         date: "2023-10-24",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Jewelry",
// //         spend: 510,
// //         percentChange: 21,
// //         absoluteChange: 107.1,
// //         date: "2023-10-27",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Seafood",
// //         spend: 230,
// //         percentChange: 7,
// //         absoluteChange: 16.1,
// //         date: "2023-10-30",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Construction",
// //         spend: 570,
// //         percentChange: 19,
// //         absoluteChange: 108.3,
// //         date: "2023-11-02",
// //       },
// //     ],
// //   },
// // ];

// export const users: User[] = [
//   {
//     id: 1,
//     name: "Aarohi Patil",
//     data: [
//       // {
//       //   sector: "Retail",
//       //   category: "Juice",
//       //   spend: 200,
//       //   percentChange: 5,
//       //   absoluteChange: 10,
//       //   date: "2023-10-01",
//       // },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 200,
//         percentChange: 5,
//         absoluteChange: 10,
//         date: "2023-10-01",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 300,
//         percentChange: 10,
//         absoluteChange: 30,
//         date: "2023-10-05",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 50,
//         percentChange: -5,
//         absoluteChange: -7.5,
//         date: "2023-10-10",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 400,
//         percentChange: 15,
//         absoluteChange: 60,
//         date: "2023-10-15",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 250,
//         percentChange: 8,
//         absoluteChange: 20,
//         date: "2023-10-20",
//       },

//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 150,
//         percentChange: -2,
//         absoluteChange: -3,
//         date: "2023-10-05",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 150,
//         percentChange: 8,
//         absoluteChange: 28,
//         date: "2023-10-10",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 220,
//         percentChange: 6,
//         absoluteChange: 13.2,
//         date: "2023-10-15",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 170,
//         percentChange: 3,
//         absoluteChange: 5.1,
//         date: "2023-10-20",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 400,
//         percentChange: 10,
//         absoluteChange: 40,
//         date: "2023-10-25",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 190,
//         percentChange: -1,
//         absoluteChange: -1.9,
//         date: "2023-10-30",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 210,
//         percentChange: 5,
//         absoluteChange: 10.5,
//         date: "2023-11-01",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 420,
//         percentChange: 12,
//         absoluteChange: 50.4,
//         date: "2023-11-05",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 240,
//         percentChange: 8,
//         absoluteChange: 19.2,
//         date: "2023-11-10",
//       },
//     ],
//   },
//   {
//     id: 2,
//     name: "Bhushan Deshmukh",
//     data: [
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 380,
//         percentChange: 9,
//         absoluteChange: 34.2,
//         date: "2023-10-03",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 180,
//         percentChange: 3,
//         absoluteChange: 5.4,
//         date: "2023-10-08",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 160,
//         percentChange: -4,
//         absoluteChange: -6.4,
//         date: "2023-10-13",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 410,
//         percentChange: 11,
//         absoluteChange: 45.1,
//         date: "2023-10-18",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 210,
//         percentChange: 7,
//         absoluteChange: 14.7,
//         date: "2023-10-23",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 140,
//         percentChange: 2,
//         absoluteChange: 2.8,
//         date: "2023-10-28",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 430,
//         percentChange: 13,
//         absoluteChange: 55.9,
//         date: "2023-11-02",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 200,
//         percentChange: 5,
//         absoluteChange: 10,
//         date: "2023-11-07",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 180,
//         percentChange: -2,
//         absoluteChange: -3.6,
//         date: "2023-11-12",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 450,
//         percentChange: 15,
//         absoluteChange: 67.5,
//         date: "2023-11-17",
//       },
//     ],
//   },
//   {
//     id: 3,
//     name: "Chhaya Joshi",
//     data: [
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 250,
//         percentChange: 8,
//         absoluteChange: 20,
//         date: "2023-10-04",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 130,
//         percentChange: -3,
//         absoluteChange: -3.9,
//         date: "2023-10-09",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 460,
//         percentChange: 14,
//         absoluteChange: 64.4,
//         date: "2023-10-14",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 150,
//         percentChange: 1,
//         absoluteChange: 1.5,
//         date: "2023-10-19",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 170,
//         percentChange: 4,
//         absoluteChange: 6.8,
//         date: "2023-10-24",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 480,
//         percentChange: 16,
//         absoluteChange: 76.8,
//         date: "2023-10-29",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 270,
//         percentChange: 10,
//         absoluteChange: 27,
//         date: "2023-11-03",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 190,
//         percentChange: -1,
//         absoluteChange: -1.9,
//         date: "2023-11-08",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 500,
//         percentChange: 18,
//         absoluteChange: 90,
//         date: "2023-11-13",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 210,
//         percentChange: 5,
//         absoluteChange: 10.5,
//         date: "2023-11-18",
//       },
//     ],
//   },
//   {
//     id: 4,
//     name: "Dinesh Kulkarni",
//     data: [
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 390,
//         percentChange: 10,
//         absoluteChange: 39,
//         date: "2023-10-06",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 190,
//         percentChange: 4,
//         absoluteChange: 7.6,
//         date: "2023-10-11",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 120,
//         percentChange: -5,
//         absoluteChange: -6,
//         date: "2023-10-16",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 420,
//         percentChange: 12,
//         absoluteChange: 50.4,
//         date: "2023-10-21",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 210,
//         percentChange: 6,
//         absoluteChange: 12.6,
//         date: "2023-10-26",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 140,
//         percentChange: 2,
//         absoluteChange: 2.8,
//         date: "2023-10-31",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 440,
//         percentChange: 14,
//         absoluteChange: 61.6,
//         date: "2023-11-04",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 230,
//         percentChange: 8,
//         absoluteChange: 18.4,
//         date: "2023-11-09",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 160,
//         percentChange: 4,
//         absoluteChange: 6.4,
//         date: "2023-11-14",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 470,
//         percentChange: 17,
//         absoluteChange: 79.9,
//         date: "2023-11-19",
//       },
//     ],
//   },
//   {
//     id: 5,
//     name: "Esha Pawar",
//     data: [
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 200,
//         percentChange: 5,
//         absoluteChange: 10,
//         date: "2023-10-07",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 370,
//         percentChange: 9,
//         absoluteChange: 33.3,
//         date: "2023-10-12",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 230,
//         percentChange: 7,
//         absoluteChange: 16.1,
//         date: "2023-10-17",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 110,
//         percentChange: -6,
//         absoluteChange: -6.6,
//         date: "2023-10-22",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 400,
//         percentChange: 11,
//         absoluteChange: 44,
//         date: "2023-10-27",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 250,
//         percentChange: 9,
//         absoluteChange: 22.5,
//         date: "2023-11-01",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 130,
//         percentChange: 1,
//         absoluteChange: 1.3,
//         date: "2023-11-06",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 430,
//         percentChange: 13,
//         absoluteChange: 55.9,
//         date: "2023-11-11",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 270,
//         percentChange: 11,
//         absoluteChange: 29.7,
//         date: "2023-11-16",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 150,
//         percentChange: 3,
//         absoluteChange: 4.5,
//         date: "2023-11-21",
//       },
//     ],
//   },
// ];

// import { User } from "../type/types";

// // export const users: User[] = [
// //   {
// //     id: 1,
// //     name: "Alice",
// //     data: [
// //       {
// //         sector: "Retail",
// //         category: "Juice",
// //         spend: 200,
// //         percentChange: 5,
// //         absoluteChange: 10,
// //         date: "2023-10-01",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Snacks",
// //         spend: 150,
// //         percentChange: -2,
// //         absoluteChange: -3,
// //         date: "2023-10-05",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Software",
// //         spend: 450,
// //         percentChange: 12,
// //         absoluteChange: 54,
// //         date: "2023-10-08",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Supplements",
// //         spend: 120,
// //         percentChange: 3,
// //         absoluteChange: 3.6,
// //         date: "2023-10-12",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Accessories",
// //         spend: 280,
// //         percentChange: -5,
// //         absoluteChange: -14,
// //         date: "2023-10-15",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Clothing",
// //         spend: 320,
// //         percentChange: 8,
// //         absoluteChange: 25.6,
// //         date: "2023-10-18",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Beverages",
// //         spend: 90,
// //         percentChange: -1,
// //         absoluteChange: -0.9,
// //         date: "2023-10-22",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Materials",
// //         spend: 410,
// //         percentChange: 15,
// //         absoluteChange: 61.5,
// //         date: "2023-10-25",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Gadgets",
// //         spend: 520,
// //         percentChange: 20,
// //         absoluteChange: 104,
// //         date: "2023-10-28",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Equipment",
// //         spend: 380,
// //         percentChange: -3,
// //         absoluteChange: -11.4,
// //         date: "2023-10-31",
// //       },
// //     ],
// //   },
// //   {
// //     id: 2,
// //     name: "Bob",
// //     data: [
// //       {
// //         sector: "Industrial",
// //         category: "Tools",
// //         spend: 300,
// //         percentChange: 10,
// //         absoluteChange: 30,
// //         date: "2023-10-03",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Juice",
// //         spend: 180,
// //         percentChange: 3,
// //         absoluteChange: 5,
// //         date: "2023-10-08",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Groceries",
// //         spend: 220,
// //         percentChange: 4,
// //         absoluteChange: 8.8,
// //         date: "2023-10-11",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Hardware",
// //         spend: 510,
// //         percentChange: 18,
// //         absoluteChange: 91.8,
// //         date: "2023-10-14",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Medicines",
// //         spend: 160,
// //         percentChange: -2,
// //         absoluteChange: -3.2,
// //         date: "2023-10-17",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Parts",
// //         spend: 290,
// //         percentChange: 7,
// //         absoluteChange: 20.3,
// //         date: "2023-10-20",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Electronics",
// //         spend: 430,
// //         percentChange: 12,
// //         absoluteChange: 51.6,
// //         date: "2023-10-23",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Organic",
// //         spend: 140,
// //         percentChange: 5,
// //         absoluteChange: 7,
// //         date: "2023-10-26",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Machinery",
// //         spend: 670,
// //         percentChange: 22,
// //         absoluteChange: 147.4,
// //         date: "2023-10-29",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Services",
// //         spend: 390,
// //         percentChange: -4,
// //         absoluteChange: -15.6,
// //         date: "2023-11-01",
// //       },
// //     ],
// //   },
// //   {
// //     id: 3,
// //     name: "Charlie",
// //     data: [
// //       {
// //         sector: "Technology",
// //         category: "Software",
// //         spend: 480,
// //         percentChange: 15,
// //         absoluteChange: 72,
// //         date: "2023-10-02",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Equipment",
// //         spend: 310,
// //         percentChange: 8,
// //         absoluteChange: 24.8,
// //         date: "2023-10-06",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Furniture",
// //         spend: 420,
// //         percentChange: 10,
// //         absoluteChange: 42,
// //         date: "2023-10-09",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Bakery",
// //         spend: 110,
// //         percentChange: -3,
// //         absoluteChange: -3.3,
// //         date: "2023-10-13",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Tires",
// //         spend: 380,
// //         percentChange: 12,
// //         absoluteChange: 45.6,
// //         date: "2023-10-16",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Chemicals",
// //         spend: 540,
// //         percentChange: 18,
// //         absoluteChange: 97.2,
// //         date: "2023-10-19",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Accessories",
// //         spend: 230,
// //         percentChange: 6,
// //         absoluteChange: 13.8,
// //         date: "2023-10-22",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Diagnostics",
// //         spend: 270,
// //         percentChange: -1,
// //         absoluteChange: -2.7,
// //         date: "2023-10-25",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Appliances",
// //         spend: 590,
// //         percentChange: 20,
// //         absoluteChange: 118,
// //         date: "2023-10-28",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Dairy",
// //         spend: 130,
// //         percentChange: 2,
// //         absoluteChange: 2.6,
// //         date: "2023-10-31",
// //       },
// //     ],
// //   },
// //   {
// //     id: 4,
// //     name: "Diana",
// //     data: [
// //       {
// //         sector: "Healthcare",
// //         category: "Wellness",
// //         spend: 190,
// //         percentChange: 6,
// //         absoluteChange: 11.4,
// //         date: "2023-10-04",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Services",
// //         spend: 250,
// //         percentChange: 8,
// //         absoluteChange: 20,
// //         date: "2023-10-07",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Sports",
// //         spend: 330,
// //         percentChange: 12,
// //         absoluteChange: 39.6,
// //         date: "2023-10-10",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Meat",
// //         spend: 170,
// //         percentChange: -4,
// //         absoluteChange: -6.8,
// //         date: "2023-10-14",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Safety",
// //         spend: 410,
// //         percentChange: 14,
// //         absoluteChange: 57.4,
// //         date: "2023-10-17",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Cloud",
// //         spend: 620,
// //         percentChange: 25,
// //         absoluteChange: 155,
// //         date: "2023-10-20",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Therapy",
// //         spend: 280,
// //         percentChange: 7,
// //         absoluteChange: 19.6,
// //         date: "2023-10-23",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Batteries",
// //         spend: 350,
// //         percentChange: -2,
// //         absoluteChange: -7,
// //         date: "2023-10-26",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Books",
// //         spend: 210,
// //         percentChange: 5,
// //         absoluteChange: 10.5,
// //         date: "2023-10-29",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Produce",
// //         spend: 140,
// //         percentChange: 3,
// //         absoluteChange: 4.2,
// //         date: "2023-11-01",
// //       },
// //     ],
// //   },
// //   {
// //     id: 5,
// //     name: "Ethan",
// //     data: [
// //       {
// //         sector: "Automotive",
// //         category: "Lubricants",
// //         spend: 270,
// //         percentChange: 9,
// //         absoluteChange: 24.3,
// //         date: "2023-10-05",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Toys",
// //         spend: 180,
// //         percentChange: 4,
// //         absoluteChange: 7.2,
// //         date: "2023-10-09",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Frozen",
// //         spend: 150,
// //         percentChange: -1,
// //         absoluteChange: -1.5,
// //         date: "2023-10-12",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Packaging",
// //         spend: 390,
// //         percentChange: 13,
// //         absoluteChange: 50.7,
// //         date: "2023-10-15",
// //       },
// //       {
// //         sector: "Technology",
// //         category: "Security",
// //         spend: 480,
// //         percentChange: 17,
// //         absoluteChange: 81.6,
// //         date: "2023-10-18",
// //       },
// //       {
// //         sector: "Healthcare",
// //         category: "Devices",
// //         spend: 320,
// //         percentChange: 10,
// //         absoluteChange: 32,
// //         date: "2023-10-21",
// //       },
// //       {
// //         sector: "Automotive",
// //         category: "Electronics",
// //         spend: 290,
// //         percentChange: -3,
// //         absoluteChange: -8.7,
// //         date: "2023-10-24",
// //       },
// //       {
// //         sector: "Retail",
// //         category: "Jewelry",
// //         spend: 510,
// //         percentChange: 21,
// //         absoluteChange: 107.1,
// //         date: "2023-10-27",
// //       },
// //       {
// //         sector: "Food",
// //         category: "Seafood",
// //         spend: 230,
// //         percentChange: 7,
// //         absoluteChange: 16.1,
// //         date: "2023-10-30",
// //       },
// //       {
// //         sector: "Industrial",
// //         category: "Construction",
// //         spend: 570,
// //         percentChange: 19,
// //         absoluteChange: 108.3,
// //         date: "2023-11-02",
// //       },
// //     ],
// //   },
// // ];

// export const users: User[] = [
//   {
//     id: 1,
//     name: "Aarohi Patil",
//     data: [
//       // {
//       //   sector: "Retail",
//       //   category: "Juice",
//       //   spend: 200,
//       //   percentChange: 5,
//       //   absoluteChange: 10,
//       //   date: "2023-10-01",
//       // },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 200,
//         percentChange: 5,
//         absoluteChange: 10,
//         date: "2023-10-01",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 300,
//         percentChange: 10,
//         absoluteChange: 30,
//         date: "2023-10-05",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 50,
//         percentChange: -5,
//         absoluteChange: -7.5,
//         date: "2023-10-10",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 400,
//         percentChange: 15,
//         absoluteChange: 60,
//         date: "2023-10-15",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 250,
//         percentChange: 8,
//         absoluteChange: 20,
//         date: "2023-10-20",
//       },

//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 150,
//         percentChange: -2,
//         absoluteChange: -3,
//         date: "2023-10-05",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 150,
//         percentChange: 8,
//         absoluteChange: 28,
//         date: "2023-10-10",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 220,
//         percentChange: 6,
//         absoluteChange: 13.2,
//         date: "2023-10-15",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 170,
//         percentChange: 3,
//         absoluteChange: 5.1,
//         date: "2023-10-20",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 400,
//         percentChange: 10,
//         absoluteChange: 40,
//         date: "2023-10-25",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 190,
//         percentChange: -1,
//         absoluteChange: -1.9,
//         date: "2023-10-30",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 210,
//         percentChange: 5,
//         absoluteChange: 10.5,
//         date: "2023-11-01",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 420,
//         percentChange: 12,
//         absoluteChange: 50.4,
//         date: "2023-11-05",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 240,
//         percentChange: 8,
//         absoluteChange: 19.2,
//         date: "2023-11-10",
//       },
//     ],
//   },
//   {
//     id: 2,
//     name: "Bhushan Deshmukh",
//     data: [
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 380,
//         percentChange: 9,
//         absoluteChange: 34.2,
//         date: "2023-10-03",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 180,
//         percentChange: 3,
//         absoluteChange: 5.4,
//         date: "2023-10-08",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 160,
//         percentChange: -4,
//         absoluteChange: -6.4,
//         date: "2023-10-13",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 410,
//         percentChange: 11,
//         absoluteChange: 45.1,
//         date: "2023-10-18",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 210,
//         percentChange: 7,
//         absoluteChange: 14.7,
//         date: "2023-10-23",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 140,
//         percentChange: 2,
//         absoluteChange: 2.8,
//         date: "2023-10-28",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 430,
//         percentChange: 13,
//         absoluteChange: 55.9,
//         date: "2023-11-02",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 200,
//         percentChange: 5,
//         absoluteChange: 10,
//         date: "2023-11-07",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 180,
//         percentChange: -2,
//         absoluteChange: -3.6,
//         date: "2023-11-12",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 450,
//         percentChange: 15,
//         absoluteChange: 67.5,
//         date: "2023-11-17",
//       },
//     ],
//   },
//   {
//     id: 3,
//     name: "Chhaya Joshi",
//     data: [
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 250,
//         percentChange: 8,
//         absoluteChange: 20,
//         date: "2023-10-04",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 130,
//         percentChange: -3,
//         absoluteChange: -3.9,
//         date: "2023-10-09",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 460,
//         percentChange: 14,
//         absoluteChange: 64.4,
//         date: "2023-10-14",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 150,
//         percentChange: 1,
//         absoluteChange: 1.5,
//         date: "2023-10-19",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 170,
//         percentChange: 4,
//         absoluteChange: 6.8,
//         date: "2023-10-24",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 480,
//         percentChange: 16,
//         absoluteChange: 76.8,
//         date: "2023-10-29",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 270,
//         percentChange: 10,
//         absoluteChange: 27,
//         date: "2023-11-03",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 190,
//         percentChange: -1,
//         absoluteChange: -1.9,
//         date: "2023-11-08",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 500,
//         percentChange: 18,
//         absoluteChange: 90,
//         date: "2023-11-13",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 210,
//         percentChange: 5,
//         absoluteChange: 10.5,
//         date: "2023-11-18",
//       },
//     ],
//   },
//   {
//     id: 4,
//     name: "Dinesh Kulkarni",
//     data: [
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 390,
//         percentChange: 10,
//         absoluteChange: 39,
//         date: "2023-10-06",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 190,
//         percentChange: 4,
//         absoluteChange: 7.6,
//         date: "2023-10-11",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 120,
//         percentChange: -5,
//         absoluteChange: -6,
//         date: "2023-10-16",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 420,
//         percentChange: 12,
//         absoluteChange: 50.4,
//         date: "2023-10-21",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 210,
//         percentChange: 6,
//         absoluteChange: 12.6,
//         date: "2023-10-26",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 140,
//         percentChange: 2,
//         absoluteChange: 2.8,
//         date: "2023-10-31",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 440,
//         percentChange: 14,
//         absoluteChange: 61.6,
//         date: "2023-11-04",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 230,
//         percentChange: 8,
//         absoluteChange: 18.4,
//         date: "2023-11-09",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 160,
//         percentChange: 4,
//         absoluteChange: 6.4,
//         date: "2023-11-14",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 470,
//         percentChange: 17,
//         absoluteChange: 79.9,
//         date: "2023-11-19",
//       },
//     ],
//   },
//   {
//     id: 5,
//     name: "Esha Pawar",
//     data: [
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 200,
//         percentChange: 5,
//         absoluteChange: 10,
//         date: "2023-10-07",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 370,
//         percentChange: 9,
//         absoluteChange: 33.3,
//         date: "2023-10-12",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 230,
//         percentChange: 7,
//         absoluteChange: 16.1,
//         date: "2023-10-17",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 110,
//         percentChange: -6,
//         absoluteChange: -6.6,
//         date: "2023-10-22",
//       },
//       {
//         sector: "Industrial",
//         category: "Juice",
//         spend: 400,
//         percentChange: 11,
//         absoluteChange: 44,
//         date: "2023-10-27",
//       },
//       {
//         sector: "Retail",
//         category: "Snacks",
//         spend: 250,
//         percentChange: 9,
//         absoluteChange: 22.5,
//         date: "2023-11-01",
//       },
//       {
//         sector: "Food",
//         category: "Juice",
//         spend: 130,
//         percentChange: 1,
//         absoluteChange: 1.3,
//         date: "2023-11-06",
//       },
//       {
//         sector: "Industrial",
//         category: "Snacks",
//         spend: 430,
//         percentChange: 13,
//         absoluteChange: 55.9,
//         date: "2023-11-11",
//       },
//       {
//         sector: "Retail",
//         category: "Juice",
//         spend: 270,
//         percentChange: 11,
//         absoluteChange: 29.7,
//         date: "2023-11-16",
//       },
//       {
//         sector: "Food",
//         category: "Snacks",
//         spend: 150,
//         percentChange: 3,
//         absoluteChange: 4.5,
//         date: "2023-11-21",
//       },
//     ],
//   },
// ];

import { User } from "../type/types";

export const users: User[] = [
  {
    id: 1,
    name: "Aarohi Patil",
    data: [
      {
        sector: "Industrial",
        category: "Snacks",
        spend: 431,
        percentChange: 9,
        absoluteChange: 26.69,
        date: "2025-02-07",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 323,
        percentChange: 3,
        absoluteChange: 24.12,
        date: "2025-01-14",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 356,
        percentChange: 8,
        absoluteChange: -36.23,
        date: "2025-03-15",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 490,
        percentChange: 2,
        absoluteChange: -6.42,
        date: "2025-02-07",
      },
      {
        sector: "Industrial",
        category: "Snacks",
        spend: 155,
        percentChange: -7,
        absoluteChange: 40.98,
        date: "2025-02-14",
      },
      {
        sector: "Industrial",
        category: "Juice",
        spend: 126,
        percentChange: 2,
        absoluteChange: 45.17,
        date: "2025-01-10",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 464,
        percentChange: 10,
        absoluteChange: -29.75,
        date: "2025-03-29",
      },
      {
        sector: "Industrial",
        category: "Snacks",
        spend: 375,
        percentChange: -5,
        absoluteChange: -9.43,
        date: "2025-03-08",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 224,
        percentChange: 13,
        absoluteChange: 31.85,
        date: "2025-03-26",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 170,
        percentChange: -4,
        absoluteChange: 41.21,
        date: "2025-01-04",
      },
    ],
  },
  {
    id: 2,
    name: "Bhushan Deshmukh",
    data: [
      {
        sector: "Industrial",
        category: "Juice",
        spend: 242,
        percentChange: 12,
        absoluteChange: 9.85,
        date: "2025-03-26",
      },
      {
        sector: "Food",
        category: "Juice",
        spend: 467,
        percentChange: -10,
        absoluteChange: -14.83,
        date: "2025-01-27",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 496,
        percentChange: 2,
        absoluteChange: 12.8,
        date: "2025-03-31",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 288,
        percentChange: 19,
        absoluteChange: 21.51,
        date: "2025-02-23",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 475,
        percentChange: 16,
        absoluteChange: -21.76,
        date: "2025-02-11",
      },
      {
        sector: "Industrial",
        category: "Juice",
        spend: 483,
        percentChange: 3,
        absoluteChange: 13.81,
        date: "2025-02-24",
      },
      {
        sector: "Industrial",
        category: "Snacks",
        spend: 393,
        percentChange: -5,
        absoluteChange: -29.37,
        date: "2025-03-08",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 457,
        percentChange: 11,
        absoluteChange: 28.27,
        date: "2025-02-17",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 238,
        percentChange: 4,
        absoluteChange: 32.09,
        date: "2025-01-28",
      },
      {
        sector: "Industrial",
        category: "Snacks",
        spend: 121,
        percentChange: -2,
        absoluteChange: 16.22,
        date: "2025-04-01",
      },
    ],
  },
  {
    id: 3,
    name: "Chhaya Joshi",
    data: [
      {
        sector: "Retail",
        category: "Snacks",
        spend: 200,
        percentChange: -10,
        absoluteChange: -30.89,
        date: "2025-04-10",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 314,
        percentChange: 9,
        absoluteChange: -49.58,
        date: "2025-04-19",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 494,
        percentChange: 7,
        absoluteChange: -46.87,
        date: "2025-01-22",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 398,
        percentChange: -8,
        absoluteChange: 20.91,
        date: "2025-02-22",
      },
      {
        sector: "Industrial",
        category: "Juice",
        spend: 455,
        percentChange: 3,
        absoluteChange: -39.07,
        date: "2025-04-05",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 475,
        percentChange: -9,
        absoluteChange: 40.97,
        date: "2025-02-20",
      },
      {
        sector: "Food",
        category: "Juice",
        spend: 305,
        percentChange: 4,
        absoluteChange: 13.93,
        date: "2025-01-24",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 119,
        percentChange: -5,
        absoluteChange: 28.16,
        date: "2025-03-03",
      },
      {
        sector: "Food",
        category: "Juice",
        spend: 141,
        percentChange: 0,
        absoluteChange: 22.79,
        date: "2025-03-29",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 230,
        percentChange: 4,
        absoluteChange: 38.52,
        date: "2025-02-10",
      },
    ],
  },
  {
    id: 4,
    name: "Dinesh Kulkarni",
    data: [
      {
        sector: "Food",
        category: "Juice",
        spend: 316,
        percentChange: 19,
        absoluteChange: 6.93,
        date: "2025-03-26",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 109,
        percentChange: 8,
        absoluteChange: 1.83,
        date: "2025-01-22",
      },
      {
        sector: "Industrial",
        category: "Juice",
        spend: 292,
        percentChange: 14,
        absoluteChange: 44.47,
        date: "2025-04-14",
      },
      {
        sector: "Industrial",
        category: "Snacks",
        spend: 338,
        percentChange: 14,
        absoluteChange: 12.04,
        date: "2025-03-31",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 216,
        percentChange: 6,
        absoluteChange: 10.87,
        date: "2025-03-09",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 150,
        percentChange: -3,
        absoluteChange: 39.55,
        date: "2025-01-08",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 417,
        percentChange: -8,
        absoluteChange: -38.41,
        date: "2025-02-20",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 467,
        percentChange: -7,
        absoluteChange: 39.05,
        date: "2025-01-20",
      },
      {
        sector: "Industrial",
        category: "Juice",
        spend: 455,
        percentChange: 2,
        absoluteChange: -29.79,
        date: "2025-01-18",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 271,
        percentChange: 2,
        absoluteChange: 10.21,
        date: "2025-01-03",
      },
    ],
  },
  {
    id: 5,
    name: "Esha Pawar",
    data: [
      {
        sector: "Retail",
        category: "Juice",
        spend: 344,
        percentChange: 15,
        absoluteChange: -2.16,
        date: "2025-02-19",
      },
      {
        sector: "Industrial",
        category: "Juice",
        spend: 443,
        percentChange: 0,
        absoluteChange: 48.06,
        date: "2025-02-27",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 354,
        percentChange: -8,
        absoluteChange: 31.4,
        date: "2025-03-17",
      },
      {
        sector: "Industrial",
        category: "Juice",
        spend: 154,
        percentChange: 7,
        absoluteChange: 34.97,
        date: "2025-04-04",
      },
      {
        sector: "Food",
        category: "Juice",
        spend: 449,
        percentChange: 11,
        absoluteChange: 6.28,
        date: "2025-01-08",
      },
      {
        sector: "Industrial",
        category: "Snacks",
        spend: 480,
        percentChange: 4,
        absoluteChange: 36.9,
        date: "2025-01-08",
      },
      {
        sector: "Retail",
        category: "Snacks",
        spend: 275,
        percentChange: 0,
        absoluteChange: 12.37,
        date: "2025-03-03",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 431,
        percentChange: -3,
        absoluteChange: -40.4,
        date: "2025-02-05",
      },
      {
        sector: "Retail",
        category: "Juice",
        spend: 356,
        percentChange: -4,
        absoluteChange: 38.22,
        date: "2025-01-16",
      },
      {
        sector: "Food",
        category: "Snacks",
        spend: 431,
        percentChange: 6,
        absoluteChange: -38.32,
        date: "2025-04-01",
      },
    ],
  },
];
